### ISSUE TITLE
CreditAccount_Ошибка расчета процентов при положительном балансе

### ISSUE THREAD

**Issue by Vladimir-Arg** [Vladimir-Arg/javaqa-team-diplom-2#1]
# Описание
Если баланс положительный, то срабатывает формула расчета процента по кредитам

# Локация дефекта
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/938ba18e8715efdbcec932b1fa87ef4f3e173ed1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения
1.  Создать объект класса CreditAccount с параметрами: 
    initialBalance = 200, creditLimit = 5000, rate = 15
2. Обратиться к методу account.yearChange()
3. Выставить ожидаемый результат равный 0
4. Сравнить ОР и результат вывода метода account.yearChange()

*Ожидаемый результат:* Вывод сообщения что при положительном балансе проценты по кредиту не начисляются
*Фактический результат:* Происходит расчет процента по формуле (Баланс / 100 * процент)

# Листинг проверочного теста 
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/938ba18e8715efdbcec932b1fa87ef4f3e173ed1/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L178

**Comment by AsaulkaKsenia** [comment]
Внесены изменения в код
