### ISSUE TITLE
CreditAccount_После покупки баланс выходит за рамки лимита кредита 

### ISSUE THREAD

**Issue by Vladimir-Arg** [Vladimir-Arg/javaqa-team-diplom-2#12]
# Описание
После совершения покупки в кредит, баланс выходит за рамки лимита кредита

# Локация дефекта
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/7e01d1602ba0e7787782ab0ac6d54e4d04a0db01/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40-L50

# Шаги воспроизведения
1. Создать объект класса CreditAccount с параметрами: 
    initialBalance = 0, creditLimit = 1000, rate = 0
2. Вызвать к методу account.pay(2000)
3. Выставить ожидаемый результат равный 0
4. Сравнить ОР и результат вывода метода account.getBalance()

*Ожидаемый результат:* Операция должна завершиться вернув false и ничего не поменяв на счёте. 
*Фактический результат:* Баланс после покупки становится меньше кредитного лимита

## Листинг проверочного теста
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/38f8802eee281f930f1c6c0f4d7c23abda102305/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L156-L165

**Comment by AsaulkaKsenia** [comment]
Дописан код
