### ISSUE TITLE
CreditAccount_После покупки с дебетового баланса некорректно рассчитывается баланс 

### ISSUE THREAD

**Issue by Vladimir-Arg** [Vladimir-Arg/javaqa-team-diplom-2#13]
# Описание	
При положительном балансе, после совершения покупки  неправильно считается баланс 
# Локация дефекта
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/7e01d1602ba0e7787782ab0ac6d54e4d04a0db01/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40-L50

# Шаги воспроизведения
1. Создать объект с положительным начальным балансом, заданным кредитным лимитом
2. Вызвать к методу account.pay(amount), в котором значение "amount" будет меньше чем начальный баланс
3. Выставить ожидаемый результат равный "(начальный баланс) - (amount)"
4. Сравнить ОР и результат вывода метода account.getBalance()

*Ожидаемый результат:* ОР и результат вывода метода account.getBalance() должны быть одинаковыми
*Фактический результат:* ОР и результат вывода метода account.getBalance() неодинаковые, при этом  account.getBalance() принимает обратное значение "amount"

# Листинг проверочного теста
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/38f8802eee281f930f1c6c0f4d7c23abda102305/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L126-L135

**Comment by AsaulkaKsenia** [comment]
Дописан код
