### ISSUE TITLE
CreditAccount_Не создается аккаунт с нулевой кредитной ставкой

### ISSUE THREAD

**Issue by Vladimir-Arg** [Vladimir-Arg/javaqa-team-diplom-2#14]
# Описание
Ошибка создания кредитного аккаунта с нулевой кредитной ставкой

# Локация дефекта
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/7e01d1602ba0e7787782ab0ac6d54e4d04a0db01/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L17
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/7e01d1602ba0e7787782ab0ac6d54e4d04a0db01/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20-L24

# Шаги воспроизведения
1. Создать объект класса CreditAccount с параметрами: 
    initialBalance = 0, creditLimit = 0, rate = 0
2. Выставить ОР равный 0
3. Сравнить ОР и результат вызова метода account.getRate()

*Ожидаемый результат:* ОР и результат вывода метода account.getRate() должны быть одинаковыми
*Фактический результат:* Вызывается исключение IllegalArgumentException ("Накопительная ставка не может быть отрицательной, а у вас: " + rate)

# Листинг проверочного теста
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/38f8802eee281f930f1c6c0f4d7c23abda102305/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L65-L74

**Comment by AsaulkaKsenia** [comment]
Исправлены баги
