### ISSUE TITLE
Ошибка в поведении операции перевода если счет получателя не может принять перевод

### ISSUE THREAD

**Issue by Vladimir-Arg** [Vladimir-Arg/javaqa-team-diplom-2#16]
# Описание
Происходит некорректное списание со счета-отправителя При переводе, в случае когда с счет отправителя нет исключений, а счет получателя не может принять перевод (после перевода некорректносе состояние счета).

# Локация дефекта
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/03a633c94789d70b9f4639ebf451d54d9e251c85/src/main/java/ru/netology/javaqadiplom/Bank.java#L20-L21

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать кредитный счет-отправителя с параметрами CreditAccount (3_000, 10_000, 20)
3. Создать дебетовый счет-получателя с параметрами SavingAccount (4_000, 1_000, 10_000, 15)
4. Вызвать метод transfer на сумму 10_000
5. Выставить ОР баланса после операции перевода: счета-отправителя 3_000, ОР счета-получателя 4_000
6. Вызвать методы .getBalance() для карт отправителя и получателя, сравнить их с ОР баланса

*Ожидаемый результат:* Операция перевода не выполняется, Результаты вывода методов from.getBalance() и to.getBalance() должны быть равны начальному балансу на соответствующих картах. 
*Фактический результат:* Со счета-отправителя списалась сумма перевода, счет-получателя остается с начальным балансом

# Листинг проверочного кода
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/aa4b596018c668c34e105c032abda713e8e64cc8/src/test/java/ru/netology/javaqadiplom/BankTest.java#L182-L189
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/aa4b596018c668c34e105c032abda713e8e64cc8/src/test/java/ru/netology/javaqadiplom/BankTest.java#L120-L128

**Comment by AsaulkaKsenia** [comment]
Исправлен код
