### ISSUE TITLE
CreditAccount_Ошибка описания баланса

### ISSUE THREAD

**Issue by Vladimir-Arg** [Vladimir-Arg/javaqa-team-diplom-2#2]
# Описание
Несоответствие описания значений, которые может принимать баланс:
* Может иметь баланс вплоть до отрицательного, но до указанного кредитного лимита
* @param initialBalance - неотрицательное число, начальный баланс для счёта

# Локация дефекта
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/7e01d1602ba0e7787782ab0ac6d54e4d04a0db01/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L5
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/7e01d1602ba0e7787782ab0ac6d54e4d04a0db01/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L15

**Comment by AsaulkaKsenia** [comment]
Исправлены баги

**Comment by AsaulkaKsenia** [comment]
Исправлено
