### ISSUE TITLE
CreditAccount_Ошибка задания баланса

### ISSUE THREAD

**Issue by Vladimir-Arg** [Vladimir-Arg/javaqa-team-diplom-2#3]
# Описание
При задании начального баланса для счёта отсутствует проверка, что баланс входит в рамки заданного лимита

# Локация дефекта
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/938ba18e8715efdbcec932b1fa87ef4f3e173ed1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L25

# Шаги воспроизведения
1. Создать объект с заданным лимитом и отрицательным начальным балансом, выходящим за лимит 
2. Обратиться к методу account.getBalance()
3. Выставить ожидаемый результат равный лимиту
4. Сравнить ОР и результат вывода метода account.getBalance()

*Ожидаемый результат:* Баланс равен лимиту
*Фактический результат:* Начальный баланс принимает значение, выходящее за рамки лимита

# Листинг проверочного теста
https://github.com/Vladimir-Arg/javaqa-team-diplom-2/blob/938ba18e8715efdbcec932b1fa87ef4f3e173ed1/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L73

**Comment by AsaulkaKsenia** [comment]
Испрввлены баги
